<?php

/** Generated by Latte 3.0.24 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\wamp64\www\zivotopis-nette\app\Presentation/@layout.latte */
final class Template_fed84eb37c extends Latte\Runtime\Template
{
	public const Source = 'C:\\wamp64\\www\\zivotopis-nette\\app\\Presentation/@layout.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo '<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width">
	<link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/header.css">
    <link rel="stylesheet" href="css/motivation.css">
    <link rel="stylesheet" href="css/footer.css">


	<title>';
		if ($this->hasBlock('title')) /* line 12 */ {
			$this->renderBlock('title', [], function ($s, $type) {
				$ʟ_fi = new LR\FilterInfo($type);
				return LR\Filters::convertTo($ʟ_fi, 'html', $this->filters->filterContent('stripHtml', $ʟ_fi, $s));
			}) /* line 12 */;
			echo ' | ';
		}
		echo 'Nette Web</title>

	';
		if ($ʟ_tmp = $this->global->assets->resolve('main.js', [], true)) /* line 14 */ {
			echo $this->global->assets->renderAsset($ʟ_tmp);
		}echo '
</head>

<body>
	<header>
		<ul style="font-size: 1rem;" id="navigation">
			<li>domov</li>
			<li><a href="https://oliver-chalupka.sk/moje-vytvory.html">moje výtvory</a></li>
			<li><a href="https://oliver-chalupka.sk/spetna-vezba">spätná väzba aplikácia</a></li>
			<li>o mne</li>
		</ul>
	</header>

';
		$this->renderBlock('content', [], 'html') /* line 27 */;
		echo '
	<footer>
        <p>&copy; Oliver Chalúpka</p>
    </footer>
</body>
<script src="script/motivationList.js"></script>
<script src="script/age.js"></script>
<script>
	setMotivationLetter(motivationTextList);
</script>
</html>
';
	}
}
