<?php

/** Generated by Latte 3.0.24 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\wamp64\www\zivotopis-nette\app\Presentation\Home/default.latte */
final class Template_98853e2887 extends Latte\Runtime\Template
{
	public const Source = 'C:\\wamp64\\www\\zivotopis-nette\\app\\Presentation\\Home/default.latte';

	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		$this->renderBlock('content', get_defined_vars()) /* line 1 */;
	}


	/** {block content} on line 1 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<main>
	<h1>Životopis Olivera Chalúpku</h1>

	<div id="základné-údaje">
		<div class="block-content">
			<h2>Základné údaje</h2>
			<ul>
				<li><strong>celé meno:</strong> ';
		echo LR\Filters::escapeHtmlText($resumeData->firstname) /* line 9 */;
		echo ' ';
		echo LR\Filters::escapeHtmlText($resumeData->secondname) /* line 9 */;
		echo '</li>
				<li><strong>narodený:</strong> ';
		echo LR\Filters::escapeHtmlText($resumeData->born_age) /* line 10 */;
		echo '</li>
				<li id="age"><strong>vek:</strong> </li>
				<li><strong>bydlisko:</strong> ';
		echo LR\Filters::escapeHtmlText($resumeData->place_of_residence) /* line 12 */;
		echo '</li>
				<li><strong>vzdelanie:</strong> ';
		echo LR\Filters::escapeHtmlText($resumeData->education) /* line 13 */;
		echo '</li>
			</ul>
		</div>
		
		<div class="block-content">
			<h2>Kontakt</h2>
			<ul>
				<li><strong>email:</strong> ';
		echo LR\Filters::escapeHtmlText($contactData->email) /* line 20 */;
		echo '</li>
				<li><strong>tel.</strong> ';
		echo LR\Filters::escapeHtmlText($contactData->phone_number) /* line 21 */;
		echo '</li>
			</ul>
		</div>
		
		
	</div>
	<div  class="block-content" id="block-content-skills">
			<h2>Zručnosti</h2>
			<ul>
				<li><span class="text-of-skill"><strong>html:</strong> základy</span><span class="show-level"><span class="inner-show">s </span></span></li>

				<li><span class="text-of-skill"><strong>css:</strong> základy </span><span class="show-level"><span class="inner-show">s </span></span></li>

				<li><span class="text-of-skill"><strong>responzívnosť webových stránok:</strong> základy </span><span class="show-level"><span class="inner-show">s </span></span></li>

				<li><span class="text-of-skill"><strong>javascript:</strong> základy </span><span class="show-level"><span class="inner-show">s </span></span></li>
			</ul>
			<ul>
				<li><span class="text-of-skill"><strong>java:</strong> základy </span><span class="show-level"><span class="inner-show">s </span></span></li>

				<li><span class="text-of-skill"><strong >python:</strong> základy </span><span class="show-level"><span class="inner-show">s </span></span></li>
				
			</ul>
			<ul>
				<li><span class="text-of-skill"><strong>php:</strong> základy</span><span class="show-level" ><span class="inner-show" id="php-level">s </span></span></li>

				<li><span class="text-of-skill"><strong>Nette:</strong> základy</span><span class="show-level" ><span class="inner-show" id="nette-level">s </span></span></li>

				<li><span class="text-of-skill"><strong>SQL:</strong> prejdutie nejakých základov </span><span class="show-level" ><span class="inner-show" id="sql-line">s </span></span></li>
			</ul>
			<ul>
				<li><span class="text-of-skill"><strong>Git:</strong> základy</span><span class="show-level" ><span class="inner-show">s </span></span></li>
			</ul>
			<ul>
				<li><span class="text-of-skill"><strong>Angličtina:</strong> B1</span><span class="show-level" ><span class="inner-show" id="anj-line">s </span></span></li>
			</ul>
	</div>

	<div id="motivačný-list">
		<h2>Motivačný list</h2>
		<p><span id="tabulator-span"></span></p>
		<button id="tlačítko-motivačného-listu">čítať ďalej</button>
		
	</div>
</main>';
	}
}
